window.ContextLandingCopy = {
  "en": {
    "title": "Context — Pick up where you left off.",
    "description": "Keep your project records together. Bring the right background into your next AI conversation, with sources you can check.",
    "skip": "Skip to content",
    "navHow": "How it works",
    "navTrust": "Built on evidence",
    "navNext": "What’s next",
    "login": "Sign in",
    "lang": "Language",
    "eyebrow": "EVENT-DRIVEN CONTEXT",
    "hero1": "New conversation.",
    "hero2": "Same momentum.",
    "heroBody": "A project context layer across your AI tools. Keep decisions, conversation logs, and original files together, so your next conversation can continue with evidence.",
    "cta": "Start with a record",
    "demoLink": "Explore the idea",
    "heroNote": "For people moving a project forward across AI conversations.",
    "demoLabel": "CONTEXT IN ACTION",
    "demoTag": "Illustrative example",
    "project": "Project / Studio launch",
    "records": "Your original records",
    "r1type": "INITIAL DECISION",
    "r1": "Set the launch budget at ¥50,000.",
    "r2type": "EXPLICIT UPDATE",
    "r2": "Change the budget to ¥30,000, replacing the earlier decision.",
    "r3type": "UNCONFIRMED SUGGESTION",
    "r3": "Consider inviting an external designer.",
    "newChat": "A new conversation · with the project brief",
    "qBudget": "What’s the budget?",
    "qNext": "What’s decided?",
    "qGap": "What’s still open?",
    "answerBudget": "The current budget is ¥30,000. The explicit update replaces the earlier ¥50,000 decision.",
    "answerNext": "The budget is confirmed at ¥30,000. Bringing in an external designer is still a suggestion, not a commitment.",
    "answerGap": "There’s no confirmed decision on an external designer. The available record is only a suggestion.",
    "sourceBudget": "Sources · records 01 + 02",
    "sourceNext": "Sources · records 02 + 03",
    "sourceGap": "Source · record 03",
    "sourceNote": "Follow the evidence back to the original.",
    "stripLabel": "ONE PROJECT. CONNECTED CONTEXT.",
    "web": "Web",
    "cli": "CLI",
    "mcp": "MCP",
    "recordStrip": "Capture once. Carry the background forward.",
    "howKicker": "01 / A CONTINUOUS THREAD",
    "howTitle": "Less catching up.\nMore moving forward.",
    "howBody": "Capture with less effort. Preserve immutable events. Let plugins turn them into context your tools can share.",
    "captureTitle": "Keep what happened.",
    "captureBody": "Hooks capture activity; your agent’s recorder skill saves decisions and progress. Push from CLI or API, or add records and files on the web. UUIDs make retries safe.",
    "available": "Record foundation",
    "captureFoot": "01 — RECORD",
    "contextTitle": "Ask with the right background.",
    "contextBody": "Plugins publish a versioned project brief: goals, decisions, constraints, and open questions, with sources and coverage. Your agent reads it at the start of a conversation.",
    "planned": "Plugin capability",
    "contextFoot": "02 — RETRIEVE",
    "skillTitle": "Let useful work come to you.",
    "skillBody": "Transcription, project briefs, evidence retrieval, and daily reviews are plugins. The core stores and queries records; your agent or a processor host does the processing.",
    "skillFoot": "03 — FOLLOW THROUGH",
    "trustKicker": "02 / KEEP THE EVIDENCE",
    "trustTitle": "An answer is useful.\nIts source makes it checkable.",
    "trustBody": "Context is designed to keep original records distinct from what an agent concludes. You can see what was said, what changed, and what still needs your judgment.",
    "trust1Title": "Originals stay intact.",
    "trust1Body": "Records are append-only. Corrections are new records, so earlier information remains available.",
    "trust2Title": "Suggestions stay suggestions.",
    "trust2Body": "Original words, agent notes, and plugin results stay distinct. A suggestion is not a confirmed decision; conflicting records need explicit resolution.",
    "trust3Title": "Projects define the boundary.",
    "trust3Body": "Members can read and append within a project. Keep personal information in a private project.",
    "nextKicker": "03 / WHERE WE ARE HEADED",
    "nextTitle": "From a voice note to a daily review",
    "nextBody": "V2 prioritizes shared project work and central sign-in on the Web. Complete client and plugin flows are being validated step by step.",
    "now": "WEB FIRST",
    "nowTitle": "A shared record of your project",
    "nowBody": "Project records and members, files, source references, versioned State, and plugin configuration. Sign in with your central Integ.Life account.",
    "next": "CONTINUING VALIDATION",
    "nextText": "Automatic capture → transcription → project brief → another agent conversation → a daily review published as dated State. Mobile capture continues after the Web flow.",
    "later": "EXPLORING",
    "laterTitle": "More ways to put context to work",
    "laterBody": "More input types and plugin implementations. A plugin marketplace, cross-project aggregation, and external publishing are outside P1.",
    "closeTitle": "Keep the context.\nContinue the work.",
    "closeBody": "Start with one project and the next decision worth remembering.",
    "footer": "A product by Integ.Life",
    "footerNote": "Original records. Ongoing context.",
    "roadmapTitle": "Start with records.\nBuild toward a helpful rhythm.",
    "navConnect": "CLI & Agent setup",
    "connectKicker": "04 / CONNECT YOUR TOOLS",
    "connectTitle": "Your context.\nIn your agent’s workflow.",
    "connectBody": "Bind a project, use the authenticated CLI from local agents, and load the recorder Skill. Remote ChatGPT remains available through MCP.",
    "cliChoice": "Read and save from your terminal",
    "mcpChoice": "Give your agent access to tools",
    "skillChoice": "Teach it when and how to use context",
    "setupIntro": "The example below uses your own local instance. For an existing instance, install the CLI and replace EDC_SERVER with its HTTPS address. Local Codex and Claude use the authenticated CLI directly; remote ChatGPT uses MCP separately.",
    "cliTitle": "CLI · Install, sign in, save a record",
    "cliBuildTitle": "Build and start locally",
    "cliBuildBody": "Requires Git, Make and Go 1.26.5 or later. Run in a terminal; leave the server running. The service listens on 127.0.0.1:8080 and stores data in the repository’s data directory. Skip starting the server if you already have an instance.",
    "copyCode": "Copy",
    "cliLoginTitle": "Sign in and choose a project",
    "cliLoginBody": "Web users sign in through Integ.Life. The commands below are for a separate local CLI test account; set your own username and email. Enter passwords privately in the terminal. CLI login saves its own token.",
    "cliRecordTitle": "Append, then read it back",
    "cliRecordBody": "Replace PROJECT_ID with an accessible project, then bind this working directory. Push a note and read it back with its UUID, author, time, and source.",
    "cliNote": "The CLI assigns UUIDs and queues failed writes for retry. Use edc outbox to inspect or flush them. Preserve the same UUID and payload when retrying JSON input; query uses next_cursor for pagination.",
    "mcpTitle": "Agent · Connect local tools",
    "mcpLocalTitle": "Local Codex / Claude: direct CLI",
    "mcpLocalBody": "Complete CLI login first. Local coding agents run edc commands directly, using the private config and token already stored by the CLI. Do not register an MCP server or expose the credential file to the agent.",
    "mcpJSONBody": "For Claude Code, edc setup claude-code previews the recorder Skill and hook changes. Applying it does not add MCP and removes a legacy EDC MCP entry while preserving unrelated servers.",
    "mcpVerify": "Ask the agent to run edc whoami, edc project list, and edc query for the selected project. Seeing the actual project and saved record proves access; configuration alone does not.",
    "mcpRemoteTitle": "Remote agent: Streamable HTTP",
    "mcpRemoteBody": "For an agent that cannot start a local process, configure your own reachable HTTPS endpoint and Bearer authentication. Replace the host and token in the client’s private connection settings. These two lines show the endpoint and HTTP header, not a shell command.",
    "mcpOAuth": "OAuth clients can use the same /mcp URL when the deployment has a public base URL and OAuth discovery configured. Sign in through the authorization page. context:read permits reading; context:write permits appending and project management. Both remain subject to project membership.",
    "mcpTrouble": "If authentication fails, repeat CLI login privately with the same server and config path. If a project is missing, check the signed-in account and membership. Remote ChatGPT connection failures remain an MCP/OAuth concern.",
    "mcpDocs": "Full CLI reference ↗",
    "skillTitleSetup": "Skill · Give your agent a repeatable workflow",
    "skillSetupBody": "The official edc-recorder skill tells your agent when to save durable notes and how to read plugin State. Hook logs, deliberate notes, and plugin results remain distinguishable.",
    "skillInstallTitle": "Add the Skill to your working project",
    "skillInstallBody": "Copy the official Skill into your project and review any existing file before replacing it. edc setup claude-code previews Skill and hook changes; --apply applies them. Local clients use the Skill with direct edc CLI commands, not MCP.",
    "downloadSkill": "Download SKILL.md",
    "viewSkill": "Read the full Skill",
    "skillTryTitle": "Try it in a new conversation",
    "skillTryBody": "Replace PROJECT_ID and invoke $edc-recorder in a new conversation. Other agents can load the same skill explicitly.",
    "agentPrompt": "$edc-recorder Read project PROJECT_ID: discover State with list_state, read its project brief, then check the original records for confirmed decisions and open questions. Cite event UUIDs and report any lag. Read only for now.",
    "skillVerify": "Expect real source UUIDs and any coverage gaps. Then ask to record a decision; verify its UUID with edc get --project PROJECT_ID EVENT_ID.",
    "skillBoundary": "Installing the recorder skill does not start transcription or scheduled reviews. Those plugins need scoped authorization and an agent or processor host.",
    "skillDocs": "Codex Skill documentation ↗",
    "setupReadme": "Full CLI, HTTP and deployment reference ↗",
    "copiedCode": "Copied",
    "copyFailed": "Could not copy automatically. The text is selected; copy it manually.",
    "returnWorkspace": "Return to workspace",
    "sessionUnavailable": "Session could not be checked. You can still read this page or open the workspace to retry."
  },
  "zh-CN": {
    "title": "Context — 换一个对话，接着往前走。",
    "description": "留下项目中的原始记录，为下一次 AI 对话带去有依据的背景，让工作持续推进。",
    "skip": "跳至正文",
    "navHow": "如何使用",
    "navTrust": "有据可循",
    "navNext": "产品进展",
    "login": "登录",
    "lang": "语言",
    "eyebrow": "EVENT-DRIVEN CONTEXT",
    "hero1": "换一个对话，",
    "hero2": "接着往前走。",
    "heroBody": "跨 AI 工具的项目上下文层。把决定、对话日志和原始文件留在一起，让下一次对话带着有依据的背景继续。",
    "cta": "从一条记录开始",
    "demoLink": "看看它如何工作",
    "heroNote": "为在多个 AI 对话中，持续推进项目的人而做。",
    "demoLabel": "CONTEXT 如何连接",
    "demoTag": "概念示例",
    "project": "项目 / 工作室启动",
    "records": "你的原始记录",
    "r1type": "最初的决定",
    "r1": "启动预算定为 5 万元。",
    "r2type": "明确的更新",
    "r2": "预算改为 3 万元，取代之前的决定。",
    "r3type": "尚未确认的建议",
    "r3": "可以考虑邀请一位外部设计师。",
    "newChat": "新的对话 · 带上项目概况",
    "qBudget": "现在预算多少？",
    "qNext": "哪些已经决定？",
    "qGap": "还有什么待确认？",
    "answerBudget": "当前预算是 3 万元。明确的更新已经取代了最初 5 万元的决定。",
    "answerNext": "预算已确定为 3 万元。邀请外部设计师仍然只是建议，还不是已确认的安排。",
    "answerGap": "是否邀请外部设计师尚未确认。已有记录只提出了建议，没有最终决定。",
    "sourceBudget": "依据 · 记录 01 + 02",
    "sourceNext": "依据 · 记录 02 + 03",
    "sourceGap": "依据 · 记录 03",
    "sourceNote": "每个结论，都能沿着依据回到原文。",
    "stripLabel": "同一个项目，连贯的上下文。",
    "web": "网页",
    "cli": "CLI",
    "mcp": "MCP",
    "recordStrip": "记录一次，让背景跟上你的工作。",
    "howKicker": "01 / 让工作连起来",
    "howTitle": "少一点重复交代，\n多一点继续向前。",
    "howBody": "省力地写入，原样地保存，再由插件整理为各个工具都能使用的上下文。",
    "captureTitle": "留下发生过的事。",
    "captureBody": "Hook 自动留下活动日志，agent 的记录 skill 主动保存决定和进展。CLI、API 随时推送，网页也能添加记录与文件；UUID 让重复提交不重复记。",
    "available": "记录基础",
    "captureFoot": "01 — 记录",
    "contextTitle": "带着背景，问下一个问题。",
    "contextBody": "插件发布有版本的项目概况：目标、当前决定、约束和未解决问题，附带来源与覆盖范围。新对话开始时，agent 就能读取它。",
    "planned": "插件能力",
    "contextFoot": "02 — 提取",
    "skillTitle": "让有用的整理主动发生。",
    "skillBody": "转录、项目概况、证据检索和每日回顾都由插件提供。核心负责保存与查询，处理工作交给你的 agent 或独立处理器。",
    "skillFoot": "03 — 推进",
    "trustKicker": "02 / 让依据留下来",
    "trustTitle": "答案有用，\n出处让它值得检查。",
    "trustBody": "Context 的设计将原始记录与 agent 的判断分开。你能看清说过什么、改过什么，以及哪些地方还需要自己判断。",
    "trust1Title": "原文保留原样。",
    "trust1Body": "记录只能追加。纠正也是一条新记录，早先的信息仍然可查。",
    "trust2Title": "建议不等于决定。",
    "trust2Body": "用户原话、agent 记录和插件结果分开标明。建议不是已确认的决定；互相矛盾的记录需要明确解决。",
    "trust3Title": "项目就是共享边界。",
    "trust3Body": "成员可读取项目历史并追加记录。私人信息放在私人项目里。",
    "nextKicker": "03 / 产品正在走向哪里",
    "nextTitle": "从一段语音，到一份每日回顾",
    "nextBody": "V2 优先交付 Web 项目协作与中心登录；跨客户端和插件的完整使用链路按步骤持续验证。",
    "now": "WEB 优先",
    "nowTitle": "留下一份共享的项目记录",
    "nowBody": "项目记录与成员、文件、来源引用、版本化 State 和插件配置。通过 Integ.Life 中心账号登录。",
    "next": "继续验证完整链路",
    "nextText": "自动记录 → 转录 → 项目概况 → 换一个 agent 继续 → 按日期发布为 State 的每日回顾。手机记录在 Web 主链之后继续推进。",
    "later": "后续探索",
    "laterTitle": "让更多信息，带来有用的行动",
    "laterBody": "扩展输入类型与插件实现。插件市场、跨项目聚合和外部发布不在 P1 范围内。",
    "closeTitle": "留下上下文，\n把事情继续下去。",
    "closeBody": "从一个项目，和下一个值得记住的决定开始。",
    "footer": "Integ.Life 出品",
    "footerNote": "原始记录，持续生长的上下文。",
    "roadmapTitle": "从记下来，\n到帮你持续推进。",
    "navConnect": "CLI 与 Agent 接入",
    "connectKicker": "04 / 连接你的工具",
    "connectTitle": "让项目上下文，\n进入 Agent 的工作流。",
    "connectBody": "绑定项目，让本地 Agent 直接使用已登录的 CLI，并加载记录 Skill。远程 ChatGPT 仍通过 MCP 接入。",
    "cliChoice": "在终端直接读取和保存",
    "mcpChoice": "让 Agent 调用项目工具",
    "skillChoice": "告诉 Agent 何时、如何使用上下文",
    "setupIntro": "以下以你自己的本地实例为例。已有服务时，只需安装 CLI，并将 EDC_SERVER 换成该实例的 HTTPS 地址。本地 Codex / Claude 直接使用已登录的 CLI；远程 ChatGPT 另行使用 MCP。",
    "cliTitle": "CLI · 安装、登录、保存第一条记录",
    "cliBuildTitle": "构建并启动本地服务",
    "cliBuildBody": "需要 Git、Make 和 Go 1.26.5 或更新版本。在终端运行，并保持服务进程开启。服务监听 127.0.0.1:8080，数据保存在仓库的 data 目录。已有实例时可跳过启动服务。",
    "cliLoginTitle": "登录并选择项目",
    "cliLoginBody": "网页使用 Integ.Life 中心登录。下方命令用于独立的本地 CLI 测试账号，请替换用户名和邮箱，并在终端私密输入密码。CLI 登录单独保存访问令牌。",
    "cliRecordTitle": "追加一条记录，再查询验证",
    "cliRecordBody": "将 PROJECT_ID 替换为有权访问的项目，再绑定当前工作目录。推送一条 note 后查询，确认它的 UUID、作者、时间和来源。",
    "cliNote": "CLI 自动生成 UUID，失败写入进入待发队列；用 edc outbox 查看或补发。重试 JSON 输入时保留原 UUID 和内容；查询分页使用 next_cursor。",
    "mcpTitle": "Agent · 接入本地工具",
    "mcpLocalTitle": "本地 Codex / Claude：直接使用 CLI",
    "mcpLocalBody": "先完成 CLI 登录。本地编程 Agent 直接运行 edc 命令，使用 CLI 已私密保存的配置和 token；不要注册 MCP，也不要让 Agent 打开凭据文件。",
    "mcpJSONBody": "Claude Code 可用 edc setup claude-code 预览记录 Skill 和 hook。应用后不会添加 MCP；若存在旧 EDC MCP 条目会将其删除，同时保留其他服务。",
    "mcpVerify": "让 Agent 运行 edc whoami、edc project list，并对选中项目执行 edc query。看到真实项目和前面保存的记录才说明接入成功；仅有配置不算。",
    "mcpRemoteTitle": "远程 Agent：Streamable HTTP",
    "mcpRemoteBody": "无法启动本地进程的 Agent，可以配置你自己的、可访问的 HTTPS 地址与 Bearer 认证。在客户端的私密连接设置中替换域名和令牌。下面两行是服务地址和 HTTP 请求头，不是终端命令。",
    "mcpOAuth": "若部署已配置公网 base URL 和 OAuth discovery，支持 OAuth 的客户端可使用同一个 /mcp 地址，并通过授权页登录。context:read 允许读取；context:write 允许追加与项目管理。两者仍受项目成员权限约束。",
    "mcpTrouble": "认证失败时，在终端里用相同服务地址和配置路径私密执行 CLI login。找不到项目时检查账号与成员身份。远程 ChatGPT 连接失败才排查 MCP/OAuth。",
    "mcpDocs": "完整 CLI 说明 ↗",
    "skillTitleSetup": "Skill · 让 Agent 按固定方式使用上下文",
    "skillSetupBody": "官方 edc-recorder skill 告诉 agent 何时记下决定和进展，以及如何读取插件 State。自动日志、主动记录和插件结果各有明确身份。",
    "skillInstallTitle": "将 Skill 放进你正在工作的项目",
    "skillInstallBody": "把官方 Skill 复制到工作项目，已有文件先比较再合并。edc setup claude-code 会预览 Skill 和 hook，--apply 才应用。本地客户端通过 Skill 直接调用 edc CLI，不使用 MCP。",
    "downloadSkill": "下载 SKILL.md",
    "viewSkill": "查看完整 Skill",
    "skillTryTitle": "在新对话里试一次",
    "skillTryBody": "替换 PROJECT_ID，在新对话中调用 $edc-recorder。其他 agent 可以显式加载同一份 skill。",
    "agentPrompt": "$edc-recorder 读取项目 PROJECT_ID：用 list_state 发现状态并读取项目概况，再查询原始记录，整理已确认决定和未解决问题。引用 event UUID，说明状态落后程度。本次只读。",
    "skillVerify": "应看到真实来源 UUID 和覆盖缺口。随后让 agent 记录一个决定，再用 edc get --project PROJECT_ID EVENT_ID 核对。",
    "skillBoundary": "安装记录 skill 不会启动转录或定时回顾。这些插件需要限定范围的授权，并由 agent 或独立处理器运行。",
    "skillDocs": "Codex Skill 官方使用说明 ↗",
    "setupReadme": "完整 CLI、HTTP 与自部署说明 ↗",
    "copyCode": "复制",
    "copiedCode": "已复制",
    "copyFailed": "无法自动复制，已选中内容，请手动复制。",
    "returnWorkspace": "返回工作区",
    "sessionUnavailable": "暂时无法确认登录状态。你仍可阅读介绍，或进入工作区重试。"
  },
  "ms": {
    "title": "Context — Sambung dari tempat anda berhenti.",
    "description": "Simpan rekod projek dan bawa latar belakang yang relevan ke perbualan AI seterusnya, dengan sumber yang boleh disemak.",
    "skip": "Langkau ke kandungan",
    "navHow": "Cara berfungsi",
    "navTrust": "Berasaskan bukti",
    "navNext": "Perkembangan",
    "login": "Log masuk",
    "lang": "Bahasa",
    "eyebrow": "EVENT-DRIVEN CONTEXT",
    "hero1": "Perbualan baharu.",
    "hero2": "Teruskan usaha.",
    "heroBody": "Lapisan konteks projek merentas alat AI. Simpan keputusan, log perbualan dan fail asal bersama supaya perbualan seterusnya boleh diteruskan dengan bukti.",
    "cta": "Mulakan dengan rekod",
    "demoLink": "Terokai konsep",
    "heroNote": "Untuk mereka yang memajukan projek melalui pelbagai perbualan AI.",
    "demoLabel": "CONTEXT DALAM TINDAKAN",
    "demoTag": "Contoh konsep",
    "project": "Projek / Pelancaran studio",
    "records": "Rekod asal anda",
    "r1type": "KEPUTUSAN AWAL",
    "r1": "Tetapkan bajet pelancaran pada ¥50,000.",
    "r2type": "KEMAS KINI JELAS",
    "r2": "Ubah bajet kepada ¥30,000, menggantikan keputusan terdahulu.",
    "r3type": "CADANGAN BELUM DISAHKAN",
    "r3": "Pertimbangkan untuk menjemput pereka luar.",
    "newChat": "Perbualan baharu · dengan ringkasan projek",
    "qBudget": "Berapa bajetnya?",
    "qNext": "Apa yang diputuskan?",
    "qGap": "Apa belum dipastikan?",
    "answerBudget": "Bajet semasa ialah ¥30,000. Kemas kini yang jelas menggantikan keputusan awal ¥50,000.",
    "answerNext": "Bajet disahkan pada ¥30,000. Melibatkan pereka luar masih satu cadangan, bukan komitmen.",
    "answerGap": "Belum ada keputusan yang disahkan tentang pereka luar. Rekod yang ada hanyalah cadangan.",
    "sourceBudget": "Sumber · rekod 01 + 02",
    "sourceNext": "Sumber · rekod 02 + 03",
    "sourceGap": "Sumber · rekod 03",
    "sourceNote": "Jejaki bukti kembali kepada rekod asal.",
    "stripLabel": "SATU PROJEK. KONTEKS BERSAMBUNG.",
    "web": "Web",
    "cli": "CLI",
    "mcp": "MCP",
    "recordStrip": "Catat sekali. Bawa latar belakang bersama.",
    "howKicker": "01 / KESINAMBUNGAN KERJA",
    "howTitle": "Kurang mengulang.\nLebih banyak kemajuan.",
    "howBody": "Catat dengan mudah. Kekalkan event asal. Plugin mengolahnya menjadi konteks yang boleh dikongsi antara alat.",
    "captureTitle": "Simpan apa yang berlaku.",
    "captureBody": "Hook merekod aktiviti; skill agent menyimpan keputusan dan kemajuan. Hantar melalui CLI atau API, atau tambah rekod dan fail melalui web. UUID mengelakkan pendua semasa percubaan semula.",
    "available": "Asas rekod",
    "captureFoot": "01 — REKOD",
    "contextTitle": "Tanya dengan latar yang tepat.",
    "contextBody": "Plugin menerbitkan ringkasan projek berversi: matlamat, keputusan, kekangan dan persoalan terbuka, dengan sumber dan liputan. Agent membacanya pada awal perbualan.",
    "planned": "Keupayaan plugin",
    "contextFoot": "02 — DAPATKAN",
    "skillTitle": "Biarkan kerja berguna datang kepada anda.",
    "skillBody": "Transkripsi, ringkasan projek, carian bukti dan ulasan harian ialah plugin. Teras menyimpan dan mencari rekod; agent atau hos pemproses melaksanakan pemprosesan.",
    "skillFoot": "03 — TERUSKAN",
    "trustKicker": "02 / SIMPAN BUKTI",
    "trustTitle": "Jawapan itu berguna.\nSumbernya boleh disemak.",
    "trustBody": "Context direka untuk membezakan rekod asal daripada kesimpulan agent. Lihat apa yang dikatakan, apa yang berubah dan apa yang masih memerlukan pertimbangan anda.",
    "trust1Title": "Rekod asal kekal.",
    "trust1Body": "Rekod hanya boleh ditambah. Pembetulan menjadi rekod baharu, jadi maklumat terdahulu masih tersedia.",
    "trust2Title": "Cadangan kekal sebagai cadangan.",
    "trust2Body": "Kata-kata asal, nota agent dan hasil plugin dibezakan. Cadangan bukan keputusan yang disahkan; rekod bercanggah perlu diselesaikan secara jelas.",
    "trust3Title": "Projek menetapkan sempadan.",
    "trust3Body": "Ahli boleh membaca dan menambah rekod dalam projek. Simpan maklumat peribadi dalam projek peribadi.",
    "nextKicker": "03 / HALA TUJU KAMI",
    "nextTitle": "Dari nota suara ke ulasan harian",
    "nextBody": "V2 mengutamakan kerja projek bersama dan log masuk pusat di Web. Aliran penuh klien dan plugin disahkan langkah demi langkah.",
    "now": "WEB DAHULU",
    "nowTitle": "Rekod projek yang dikongsi",
    "nowBody": "Rekod dan ahli projek, fail, rujukan sumber, State berversi dan konfigurasi plugin. Log masuk dengan akaun pusat Integ.Life.",
    "next": "PENGESAHAN BERTERUSAN",
    "nextText": "Rakaman automatik → transkripsi → ringkasan projek → perbualan agent baharu → ulasan harian sebagai State bertarikh. Rakaman mudah alih diteruskan selepas aliran Web.",
    "later": "PENEROKAAN",
    "laterTitle": "Lebih banyak cara menggunakan konteks",
    "laterBody": "Lebih banyak jenis input dan pelaksanaan plugin. Pasaran plugin, penggabungan merentas projek dan penerbitan luar tidak termasuk dalam P1.",
    "closeTitle": "Simpan konteks.\nTeruskan kerja.",
    "closeBody": "Mulakan dengan satu projek dan keputusan seterusnya yang patut diingati.",
    "footer": "Produk oleh Integ.Life",
    "footerNote": "Rekod asal. Konteks berterusan.",
    "roadmapTitle": "Bermula dengan rekod.\nMenuju rutin yang membantu.",
    "navConnect": "CLI & Agent",
    "connectKicker": "04 / SAMBUNGKAN ALAT",
    "connectTitle": "Konteks projek.\nDalam aliran kerja agent.",
    "connectBody": "Ikat projek, gunakan CLI yang telah log masuk daripada agent setempat dan muatkan Skill perakam. ChatGPT jauh kekal tersedia melalui MCP.",
    "cliChoice": "Baca dan simpan melalui terminal",
    "mcpChoice": "Beri agent akses kepada alat projek",
    "skillChoice": "Panduan bila dan cara menggunakan konteks",
    "setupIntro": "Contoh ini menggunakan pelayan setempat anda. Jika pelayan sudah ada, pasang CLI dan tukar EDC_SERVER kepada alamat HTTPS itu. Codex dan Claude setempat menggunakan CLI yang telah log masuk secara terus; ChatGPT jauh menggunakan MCP secara berasingan.",
    "cliTitle": "CLI · Pasang, log masuk, simpan rekod",
    "cliBuildTitle": "Bina dan jalankan pelayan setempat",
    "cliBuildBody": "Perlu Git, Make dan Go 1.26.5 atau lebih baharu. Jalankan dalam terminal dan biarkan pelayan berjalan. Alamatnya 127.0.0.1:8080; data disimpan dalam direktori data repositori. Langkau pelancaran pelayan jika anda sudah mempunyai pelayan.",
    "cliLoginTitle": "Log masuk dan pilih projek",
    "cliLoginBody": "Pengguna web log masuk melalui Integ.Life. Arahan ini untuk akaun ujian CLI setempat yang berasingan; tetapkan nama pengguna dan e-mel sendiri. Masukkan kata laluan secara peribadi. CLI menyimpan token sendiri.",
    "cliRecordTitle": "Tambah rekod, kemudian baca semula",
    "cliRecordBody": "Gantikan PROJECT_ID dengan projek yang boleh diakses, kemudian ikat direktori kerja ini. Hantar note dan baca semula UUID, penulis, masa dan sumbernya.",
    "cliNote": "CLI menjana UUID dan menyimpan penghantaran gagal dalam baris gilir. Gunakan edc outbox untuk menyemak atau menghantar semula. Kekalkan UUID dan kandungan asal apabila mencuba semula input JSON; carian berhalaman menggunakan next_cursor.",
    "mcpTitle": "Agent · Sambungkan alat setempat",
    "mcpLocalTitle": "Codex / Claude setempat: CLI terus",
    "mcpLocalBody": "Log masuk melalui CLI dahulu. Agent pengekodan setempat menjalankan arahan edc secara terus menggunakan konfigurasi dan token peribadi yang disimpan oleh CLI. Jangan daftar MCP atau buka fail kelayakan.",
    "mcpJSONBody": "Untuk Claude Code, edc setup claude-code mempratonton Skill perakam dan hook. Ia tidak menambah MCP dan membuang entri EDC MCP lama sambil mengekalkan pelayan lain.",
    "mcpVerify": "Minta agent menjalankan edc whoami, edc project list dan edc query untuk projek dipilih. Projek dan rekod sebenar membuktikan akses; konfigurasi sahaja tidak mencukupi.",
    "mcpRemoteTitle": "Agent jauh: Streamable HTTP",
    "mcpRemoteBody": "Jika agent tidak boleh menjalankan proses setempat, gunakan alamat HTTPS pelayan anda dan pengesahan Bearer. Gantikan hos dan token dalam tetapan sambungan peribadi klien. Dua baris ini ialah alamat dan pengepala HTTP, bukan arahan terminal.",
    "mcpOAuth": "Klien OAuth boleh menggunakan URL /mcp yang sama apabila pelayan mempunyai URL awam dan penemuan OAuth. Log masuk melalui halaman kebenaran. context:read membolehkan bacaan; context:write membolehkan penambahan dan pengurusan projek. Keahlian projek tetap diperlukan.",
    "mcpTrouble": "Jika pengesahan gagal, jalankan CLI login secara peribadi dengan pelayan dan laluan konfigurasi yang sama. Jika projek tiada, semak akaun dan keahlian. Hanya sambungan ChatGPT jauh menggunakan MCP/OAuth.",
    "mcpDocs": "Rujukan penuh CLI ↗",
    "skillTitleSetup": "Skill · Panduan aliran kerja agent",
    "skillSetupBody": "Skill rasmi edc-recorder mengajar agent bila perlu menyimpan nota kekal dan cara membaca State plugin. Log hook, nota dan hasil plugin kekal berbeza.",
    "skillInstallTitle": "Tambah Skill ke projek kerja anda",
    "skillInstallBody": "Salin Skill rasmi ke projek anda dan semak fail sedia ada. edc setup claude-code mempratonton Skill dan hook; --apply menerapkannya. Klien setempat menggunakan Skill dengan arahan edc CLI terus, bukan MCP.",
    "downloadSkill": "Muat turun SKILL.md",
    "viewSkill": "Baca Skill penuh",
    "skillTryTitle": "Cuba dalam perbualan baharu",
    "skillTryBody": "Gantikan PROJECT_ID dan gunakan $edc-recorder dalam perbualan baharu. Agent lain boleh memuatkan skill yang sama secara jelas.",
    "agentPrompt": "$edc-recorder Baca projek PROJECT_ID: temui State melalui list_state, baca ringkasan projek, kemudian semak rekod asal untuk keputusan dan persoalan terbuka. Petik UUID event dan laporkan lag. Baca sahaja buat masa ini.",
    "skillVerify": "Jangka UUID sumber sebenar dan jurang liputan. Kemudian minta satu keputusan direkodkan; semak melalui edc get --project PROJECT_ID EVENT_ID.",
    "skillBoundary": "Memasang skill pencatat tidak memulakan transkripsi atau ulasan berjadual. Plugin itu memerlukan kebenaran berskop serta agent atau hos pemproses.",
    "skillDocs": "Dokumentasi Skill Codex ↗",
    "setupReadme": "Rujukan penuh CLI, HTTP dan pemasangan pelayan ↗",
    "copyCode": "Salin",
    "copiedCode": "Disalin",
    "copyFailed": "Salinan automatik gagal. Teks dipilih; sila salin secara manual.",
    "returnWorkspace": "Kembali ke ruang kerja",
    "sessionUnavailable": "Sesi tidak dapat disemak. Anda masih boleh membaca halaman ini atau membuka ruang kerja untuk mencuba lagi."
  },
  "hi": {
    "title": "Context — जहाँ रुके थे, वहीं से आगे बढ़ें।",
    "description": "अपने प्रोजेक्ट के रिकॉर्ड सहेजें और जाँचे जा सकने वाले स्रोतों के साथ अगली AI बातचीत में सही संदर्भ लाएँ।",
    "skip": "मुख्य सामग्री पर जाएँ",
    "navHow": "कैसे काम करता है",
    "navTrust": "साक्ष्य पर आधारित",
    "navNext": "आगे की योजना",
    "login": "साइन इन",
    "lang": "भाषा",
    "eyebrow": "EVENT-DRIVEN CONTEXT",
    "hero1": "नई बातचीत।",
    "hero2": "काम जारी रहे।",
    "heroBody": "AI टूल्स के बीच आपके प्रोजेक्ट के संदर्भ की साझा परत। निर्णय, बातचीत के लॉग और मूल फ़ाइलें साथ रखें, ताकि अगली बातचीत साक्ष्य के साथ आगे बढ़े।",
    "cta": "एक रिकॉर्ड से शुरू करें",
    "demoLink": "विचार को समझें",
    "heroNote": "उन लोगों के लिए जो कई AI बातचीत में एक प्रोजेक्ट को आगे बढ़ाते हैं।",
    "demoLabel": "CONTEXT का उदाहरण",
    "demoTag": "अवधारणा का उदाहरण",
    "project": "प्रोजेक्ट / स्टूडियो की शुरुआत",
    "records": "आपके मूल रिकॉर्ड",
    "r1type": "शुरुआती निर्णय",
    "r1": "शुरुआत का बजट ¥50,000 तय करें।",
    "r2type": "स्पष्ट बदलाव",
    "r2": "पहले निर्णय की जगह बजट ¥30,000 करें।",
    "r3type": "अपुष्ट सुझाव",
    "r3": "किसी बाहरी डिज़ाइनर को बुलाने पर विचार करें।",
    "newChat": "नई बातचीत · प्रोजेक्ट सार के साथ",
    "qBudget": "बजट कितना है?",
    "qNext": "क्या तय हो गया है?",
    "qGap": "क्या अभी खुला है?",
    "answerBudget": "वर्तमान बजट ¥30,000 है। स्पष्ट बदलाव ने पहले के ¥50,000 वाले निर्णय की जगह ली है।",
    "answerNext": "बजट ¥30,000 तय है। बाहरी डिज़ाइनर को शामिल करना अभी सुझाव है, कोई पक्का निर्णय नहीं।",
    "answerGap": "बाहरी डिज़ाइनर पर कोई पक्का निर्णय नहीं है। उपलब्ध रिकॉर्ड केवल एक सुझाव है।",
    "sourceBudget": "स्रोत · रिकॉर्ड 01 + 02",
    "sourceNext": "स्रोत · रिकॉर्ड 02 + 03",
    "sourceGap": "स्रोत · रिकॉर्ड 03",
    "sourceNote": "साक्ष्य से मूल रिकॉर्ड तक पहुँचें।",
    "stripLabel": "एक प्रोजेक्ट। जुड़ा हुआ संदर्भ।",
    "web": "वेब",
    "cli": "CLI",
    "mcp": "MCP",
    "recordStrip": "एक बार दर्ज करें। संदर्भ साथ लेकर आगे बढ़ें।",
    "howKicker": "01 / काम की निरंतरता",
    "howTitle": "कम दोहराएँ।\nज़्यादा आगे बढ़ें।",
    "howBody": "कम मेहनत से दर्ज करें। मूल event सुरक्षित रखें। Plugin उन्हें टूल्स के बीच साझा संदर्भ में बदलते हैं।",
    "captureTitle": "जो हुआ, उसे सहेजें।",
    "captureBody": "Hook गतिविधि दर्ज करता है; agent का recorder skill निर्णय और प्रगति सहेजता है। CLI या API से भेजें, या वेब पर रिकॉर्ड और फ़ाइल जोड़ें। UUID दोबारा भेजने पर डुप्लिकेट रोकता है।",
    "available": "रिकॉर्ड का आधार",
    "captureFoot": "01 — दर्ज करें",
    "contextTitle": "सही पृष्ठभूमि के साथ पूछें।",
    "contextBody": "Plugin प्रोजेक्ट का संस्करणयुक्त सार प्रकाशित करते हैं: लक्ष्य, निर्णय, सीमाएँ और खुले प्रश्न, स्रोत और कवरेज सहित। नई बातचीत में agent इसे पढ़ता है।",
    "planned": "Plugin की क्षमता",
    "contextFoot": "02 — संदर्भ लें",
    "skillTitle": "उपयोगी काम खुद आप तक आए।",
    "skillBody": "ट्रांसक्रिप्शन, प्रोजेक्ट सार, साक्ष्य खोज और दैनिक समीक्षा plugin हैं। मुख्य सेवा रिकॉर्ड सहेजती और खोजती है; agent या अलग processor host उन्हें संसाधित करता है।",
    "skillFoot": "03 — आगे बढ़ें",
    "trustKicker": "02 / साक्ष्य बनाए रखें",
    "trustTitle": "जवाब उपयोगी है।\nस्रोत उसे जाँचने योग्य बनाता है।",
    "trustBody": "Context का डिज़ाइन मूल रिकॉर्ड और agent के निष्कर्ष को अलग रखता है। देखें कि क्या कहा गया, क्या बदला और कहाँ आपके निर्णय की ज़रूरत है।",
    "trust1Title": "मूल रिकॉर्ड जस के तस।",
    "trust1Body": "रिकॉर्ड केवल जोड़े जाते हैं। सुधार एक नया रिकॉर्ड होता है, इसलिए पुरानी जानकारी उपलब्ध रहती है।",
    "trust2Title": "सुझाव, सुझाव ही रहता है।",
    "trust2Body": "मूल शब्द, agent के नोट और plugin के परिणाम अलग रहते हैं। सुझाव पक्का निर्णय नहीं है; विरोधी रिकॉर्ड का स्पष्ट समाधान चाहिए।",
    "trust3Title": "प्रोजेक्ट सीमा तय करते हैं।",
    "trust3Body": "सदस्य प्रोजेक्ट में पढ़ सकते हैं और रिकॉर्ड जोड़ सकते हैं। निजी जानकारी निजी प्रोजेक्ट में रखें।",
    "nextKicker": "03 / आगे की दिशा",
    "nextTitle": "वॉइस नोट से दैनिक समीक्षा तक",
    "nextBody": "V2 में पहले Web पर साझा प्रोजेक्ट और केंद्रीय साइन इन हैं। पूरे क्लाइंट और plugin प्रवाह का क्रम से सत्यापन जारी है।",
    "now": "पहले WEB",
    "nowTitle": "आपके प्रोजेक्ट का साझा रिकॉर्ड",
    "nowBody": "प्रोजेक्ट रिकॉर्ड और सदस्य, फ़ाइलें, स्रोत संदर्भ, संस्करणयुक्त State और plugin सेटिंग। Integ.Life के केंद्रीय खाते से साइन इन करें।",
    "next": "सत्यापन जारी",
    "nextText": "अपने आप रिकॉर्ड → ट्रांसक्रिप्शन → प्रोजेक्ट सार → दूसरे agent में बातचीत → तारीख वाले State के रूप में दैनिक समीक्षा। Web प्रक्रिया के बाद मोबाइल रिकॉर्डिंग आगे बढ़ेगी।",
    "later": "आगे के विचार",
    "laterTitle": "संदर्भ को उपयोगी बनाने के और तरीके",
    "laterBody": "और इनपुट प्रकार और plugin कार्यान्वयन। Plugin बाज़ार, प्रोजेक्ट के बीच एकत्रीकरण और बाहरी प्रकाशन P1 में नहीं हैं।",
    "closeTitle": "संदर्भ सहेजें।\nकाम जारी रखें।",
    "closeBody": "एक प्रोजेक्ट और याद रखने लायक अगले निर्णय से शुरू करें।",
    "footer": "Integ.Life का एक उत्पाद",
    "footerNote": "मूल रिकॉर्ड। निरंतर संदर्भ।",
    "roadmapTitle": "रिकॉर्ड से शुरू करें।\nमददगार दिनचर्या की ओर बढ़ें।",
    "navConnect": "CLI और Agent",
    "connectKicker": "04 / अपने टूल जोड़ें",
    "connectTitle": "प्रोजेक्ट का संदर्भ।\nआपके agent के काम में।",
    "connectBody": "प्रोजेक्ट जोड़ें, स्थानीय agent से लॉग-इन किया CLI सीधे उपयोग करें और recorder Skill लोड करें। दूरस्थ ChatGPT के लिए MCP उपलब्ध रहता है।",
    "cliChoice": "टर्मिनल से पढ़ें और सहेजें",
    "mcpChoice": "Agent को प्रोजेक्ट के टूल दें",
    "skillChoice": "संदर्भ कब और कैसे उपयोग करना है, बताएँ",
    "setupIntro": "यह उदाहरण आपके स्थानीय सर्वर के लिए है। सर्वर पहले से है तो CLI स्थापित करें और EDC_SERVER में उसका HTTPS पता दें। स्थानीय Codex और Claude लॉग-इन किए CLI को सीधे उपयोग करते हैं; दूरस्थ ChatGPT अलग से MCP उपयोग करता है।",
    "cliTitle": "CLI · स्थापित करें, लॉग इन करें, रिकॉर्ड सहेजें",
    "cliBuildTitle": "स्थानीय सर्वर बनाएँ और चलाएँ",
    "cliBuildBody": "Git, Make और Go 1.26.5 या नया संस्करण चाहिए। टर्मिनल में चलाएँ और सर्वर चालू रखें। पता 127.0.0.1:8080 है; डेटा रिपॉज़िटरी के data फ़ोल्डर में रहेगा। सर्वर पहले से है तो उसे शुरू करने का चरण छोड़ें।",
    "cliLoginTitle": "लॉग इन करें और प्रोजेक्ट चुनें",
    "cliLoginBody": "Web उपयोगकर्ता Integ.Life से साइन इन करते हैं। ये आदेश अलग स्थानीय CLI परीक्षण खाते के लिए हैं; अपना उपयोगकर्ता नाम और ईमेल दें। पासवर्ड टर्मिनल में निजी रूप से डालें। CLI अपना टोकन सहेजता है।",
    "cliRecordTitle": "रिकॉर्ड जोड़ें और पढ़कर जाँचें",
    "cliRecordBody": "PROJECT_ID को उपलब्ध प्रोजेक्ट से बदलें और कार्य डायरेक्टरी उससे जोड़ें। एक note भेजें, फिर उसका UUID, लेखक, समय और स्रोत पढ़ें।",
    "cliNote": "CLI UUID बनाता है और विफल रिकॉर्ड कतार में रखता है। edc outbox से देखें या फिर भेजें। JSON दोबारा भेजते समय UUID और सामग्री वही रखें; खोज के अगले पृष्ठ के लिए next_cursor लें।",
    "mcpTitle": "Agent · स्थानीय टूल जोड़ें",
    "mcpLocalTitle": "स्थानीय Codex / Claude: सीधे CLI",
    "mcpLocalBody": "पहले CLI से लॉग इन करें। स्थानीय coding agent, CLI में निजी रूप से सहेजे config और token के साथ edc command सीधे चलाते हैं। MCP register न करें और credential file agent को न खोलने दें।",
    "mcpJSONBody": "Claude Code के लिए edc setup claude-code recorder Skill और hook का preview दिखाता है। यह MCP नहीं जोड़ता और अन्य server बचाते हुए पुरानी EDC MCP entry हटाता है।",
    "mcpVerify": "Agent से चुने प्रोजेक्ट के लिए edc whoami, edc project list और edc query चलवाएँ। असली प्रोजेक्ट और record दिखना ही access का प्रमाण है; configuration अकेला पर्याप्त नहीं।",
    "mcpRemoteTitle": "दूरस्थ agent: Streamable HTTP",
    "mcpRemoteBody": "स्थानीय प्रक्रिया शुरू न कर सकने वाले agent के लिए अपने सर्वर का उपलब्ध HTTPS पता और Bearer प्रमाणीकरण दें। क्लाइंट की निजी कनेक्शन सेटिंग में होस्ट और टोकन बदलें। नीचे पता और HTTP हेडर हैं, टर्मिनल कमांड नहीं।",
    "mcpOAuth": "सर्वर पर सार्वजनिक base URL और OAuth discovery सेट होने पर OAuth क्लाइंट उसी /mcp URL का उपयोग कर सकते हैं। अनुमति पृष्ठ से लॉग इन करें। context:read पढ़ने और context:write जोड़ने व प्रोजेक्ट प्रबंधन के लिए है। प्रोजेक्ट सदस्यता की जाँच दोनों में होती है।",
    "mcpTrouble": "Authentication विफल हो तो उसी server और config path के साथ terminal में निजी रूप से CLI login चलाएँ। प्रोजेक्ट न दिखे तो account और membership जाँचें। केवल दूरस्थ ChatGPT में MCP/OAuth देखें।",
    "mcpDocs": "पूरी CLI जानकारी ↗",
    "skillTitleSetup": "Skill · Agent के काम करने का तरीका तय करें",
    "skillSetupBody": "आधिकारिक edc-recorder skill agent को स्थायी नोट लिखने और plugin State पढ़ने का तरीका बताता है। Hook लॉग, नोट और plugin परिणाम अलग रहते हैं।",
    "skillInstallTitle": "अपने कार्य प्रोजेक्ट में Skill जोड़ें",
    "skillInstallBody": "आधिकारिक Skill को प्रोजेक्ट में कॉपी करें और मौजूदा फ़ाइल पहले जाँचें। edc setup claude-code Skill और hook का preview दिखाता है; --apply लागू करता है। स्थानीय client Skill के साथ सीधे edc CLI उपयोग करते हैं, MCP नहीं।",
    "downloadSkill": "SKILL.md डाउनलोड करें",
    "viewSkill": "पूरा Skill पढ़ें",
    "skillTryTitle": "नई बातचीत में आज़माएँ",
    "skillTryBody": "PROJECT_ID बदलें और नई बातचीत में $edc-recorder चलाएँ। अन्य agent यही skill सीधे पढ़ सकते हैं।",
    "agentPrompt": "$edc-recorder प्रोजेक्ट PROJECT_ID पढ़ें: list_state से State खोजें, प्रोजेक्ट सार पढ़ें, फिर पक्के निर्णय और खुले प्रश्न मूल रिकॉर्ड से जाँचें। Event UUID दें और lag बताएँ। अभी केवल पढ़ें।",
    "skillVerify": "असली स्रोत UUID और कवरेज की कमी दिखनी चाहिए। फिर निर्णय दर्ज करवाएँ और edc get --project PROJECT_ID EVENT_ID से जाँचें।",
    "skillBoundary": "Recorder skill स्थापित करने से ट्रांसक्रिप्शन या निर्धारित समीक्षा शुरू नहीं होती। उन plugin के लिए सीमित अनुमति और agent या processor host चाहिए।",
    "skillDocs": "Codex Skill के आधिकारिक निर्देश ↗",
    "setupReadme": "CLI, HTTP और स्वयं होस्ट करने का पूरा विवरण ↗",
    "copyCode": "कॉपी करें",
    "copiedCode": "कॉपी हो गया",
    "copyFailed": "अपने-आप कॉपी नहीं हुआ। चुने हुए टेक्स्ट को मैन्युअल रूप से कॉपी करें।",
    "returnWorkspace": "कार्यक्षेत्र में लौटें",
    "sessionUnavailable": "सत्र की जाँच नहीं हो सकी। आप यह पृष्ठ पढ़ सकते हैं या कार्यक्षेत्र में फिर कोशिश कर सकते हैं।"
  }
};
