window.ContextLandingCopy = {
  "en": {
    "title": "Context — Pick up where you left off.",
    "description": "Keep your project records together. Bring the right background into your next AI conversation, with sources you can check.",
    "skip": "Skip to content",
    "navHow": "How it works",
    "navTrust": "Built on evidence",
    "navNext": "What’s next",
    "login": "Open workspace",
    "lang": "Language",
    "eyebrow": "EVENT-DRIVEN CONTEXT",
    "hero1": "New conversation.",
    "hero2": "Same momentum.",
    "heroBody": "Your decisions, ideas, and project history shouldn’t end with a chat. Keep the originals. Give your next conversation the context to move forward.",
    "cta": "Start with a record",
    "demoLink": "Explore the idea",
    "heroNote": "For people moving a project forward across AI conversations.",
    "demoLabel": "CONTEXT IN ACTION",
    "demoTag": "Illustrative example",
    "project": "Project / Studio launch",
    "records": "Your original records",
    "r1type": "INITIAL DECISION",
    "r1": "Set the launch budget at ¥50,000.",
    "r2type": "EXPLICIT UPDATE",
    "r2": "Change the budget to ¥30,000, replacing the earlier decision.",
    "r3type": "UNCONFIRMED SUGGESTION",
    "r3": "Consider inviting an external designer.",
    "newChat": "A new conversation",
    "qBudget": "What’s the budget?",
    "qNext": "What’s decided?",
    "qGap": "What’s still open?",
    "answerBudget": "The current budget is ¥30,000. The explicit update replaces the earlier ¥50,000 decision.",
    "answerNext": "The budget is confirmed at ¥30,000. Bringing in an external designer is still a suggestion, not a commitment.",
    "answerGap": "There’s no confirmed decision on an external designer. The available record is only a suggestion.",
    "sourceBudget": "Sources · records 01 + 02",
    "sourceNext": "Sources · records 02 + 03",
    "sourceGap": "Source · record 03",
    "sourceNote": "Follow the evidence back to the original.",
    "stripLabel": "ONE PROJECT. CONNECTED CONTEXT.",
    "web": "Web",
    "cli": "CLI",
    "mcp": "MCP",
    "recordStrip": "Capture once. Carry the background forward.",
    "howKicker": "01 / A CONTINUOUS THREAD",
    "howTitle": "Less catching up.\nMore moving forward.",
    "howBody": "A place for the information behind your work, with context shaped around what you need next.",
    "captureTitle": "Keep what happened.",
    "captureBody": "Save text and original text files from the web, CLI, or MCP. Each record keeps its author, time, and metadata.",
    "available": "Available foundation",
    "captureFoot": "01 — RECORD",
    "contextTitle": "Ask with the right background.",
    "contextBody": "The direction: your agent retrieves relevant decisions, constraints, and open questions for the task at hand, with links to the evidence.",
    "planned": "Planned",
    "contextFoot": "02 — RETRIEVE",
    "skillTitle": "Let useful work come to you.",
    "skillBody": "Install a skill to turn a recording into text or gather a daily review. Choose its project, instructions, and execution environment.",
    "skillFoot": "03 — FOLLOW THROUGH",
    "trustKicker": "02 / KEEP THE EVIDENCE",
    "trustTitle": "An answer is useful.\nIts source makes it checkable.",
    "trustBody": "Context is designed to keep original records distinct from what an agent concludes. You can see what was said, what changed, and what still needs your judgment.",
    "trust1Title": "Originals stay intact.",
    "trust1Body": "Records are append-only. Corrections are new records, so earlier information remains available.",
    "trust2Title": "Suggestions stay suggestions.",
    "trust2Body": "The intended context flow distinguishes an idea from a decision you have actually confirmed.",
    "trust3Title": "Projects define the boundary.",
    "trust3Body": "Members can read and append within a project. Keep personal information in a private project.",
    "nextKicker": "03 / WHERE WE ARE HEADED",
    "nextTitle": "From a voice note to a daily review",
    "nextBody": "We’re developing Context one useful loop at a time. Here’s the foundation today and the next steps in the product design.",
    "now": "TODAY",
    "nowTitle": "A shared record of your project",
    "nowBody": "Projects, members, text and text files, metadata queries, and HTTP, CLI, and MCP access.",
    "next": "NEXT VALIDATION",
    "nextText": "Audio upload, skill-based transcription, retrieval with evidence, and a scheduled review in your inbox.",
    "later": "EXPLORING",
    "laterTitle": "More ways to put context to work",
    "laterBody": "Image analysis, reminders, recommendations, and sharing with explicitly configured permissions.",
    "closeTitle": "Keep the context.\nContinue the work.",
    "closeBody": "Start with one project and the next decision worth remembering.",
    "footer": "A product by Integ.Life",
    "footerNote": "Original records. Ongoing context.",
    "roadmapTitle": "Start with records.\nBuild toward a helpful rhythm.",
    "navConnect": "CLI & Agent setup",
    "connectKicker": "04 / CONNECT YOUR TOOLS",
    "connectTitle": "Your context.\nIn your agent’s workflow.",
    "connectBody": "Start with the CLI, connect your agent through MCP, then add a Skill to guide how it reads and saves project context.",
    "cliChoice": "Read and save from your terminal",
    "mcpChoice": "Give your agent access to tools",
    "skillChoice": "Teach it when and how to use context",
    "setupIntro": "The example below uses your own local instance. For an existing instance, install the CLI and replace EDC_SERVER with its HTTPS address. Keep the same account and config for CLI and MCP.",
    "cliTitle": "CLI · Install, sign in, save a record",
    "cliBuildTitle": "Build and start locally",
    "cliBuildBody": "Requires Git, Make and Go 1.26.5 or later. Run in a terminal; leave the server running. The service listens on 127.0.0.1:8080 and stores data in the repository’s data directory. Skip starting the server if you already have an instance.",
    "copyCode": "Copy",
    "cliLoginTitle": "Sign in and choose a project",
    "cliLoginBody": "Open a second terminal. Replace the repository path and alice with your own values. Existing users can skip register. Passwords are entered privately in the terminal (12–72 bytes). Login saves a token locally; no token needs to go into your prompt.",
    "cliRecordTitle": "Append, then read it back",
    "cliRecordBody": "Replace PROJECT_ID with the id returned by project create or project list. The query should return the record you just saved, with its event ID, author and time. Global flags such as --server and --config go before the command.",
    "cliNote": "Commands return JSON. query returns a page of records; pass next_cursor as --cursor with the same filters to continue. For retryable writes, provide a unique --idempotency-key and reuse it only for that write.",
    "mcpTitle": "MCP · Connect your agent",
    "mcpLocalTitle": "Local agent: stdio",
    "mcpLocalBody": "Complete CLI login first. edc mcp is a local bridge to your server, not a separate database. Replace both absolute paths below; config.json must be the file used at login (the EDC_CONFIG path above). The agent must run on a machine that can access these files and the server.",
    "mcpJSONBody": "For clients that accept mcpServers JSON, merge this entry into their MCP configuration. Choose this or the Codex command above; you only need one registration.",
    "mcpVerify": "Reconnect or restart the agent’s MCP connection. Ask it to list your Context projects with list_projects, then read one with query_events. Seeing your actual project and the record saved above verifies access; a configured-server list alone does not.",
    "mcpRemoteTitle": "Remote agent: Streamable HTTP",
    "mcpRemoteBody": "For an agent that cannot start a local process, configure your own reachable HTTPS endpoint and Bearer authentication. Replace the host and token in the client’s private connection settings. These two lines show the endpoint and HTTP header, not a shell command.",
    "mcpOAuth": "OAuth clients can use the same /mcp URL when the deployment has a public base URL and OAuth discovery configured. Sign in through the authorization page. context:read permits reading; context:write permits appending and project management. Both remain subject to project membership.",
    "mcpTrouble": "If authentication fails, repeat CLI login with the same server and config path, then reconnect. If a project is missing, check the signed-in account and membership. For remote connection failures, check that your own endpoint is reachable.",
    "mcpDocs": "Codex MCP documentation ↗",
    "skillTitleSetup": "Skill · Give your agent a repeatable workflow",
    "skillSetupBody": "MCP supplies tools; a Skill supplies instructions. This event-context Skill asks your agent to read relevant history, cite sources, distinguish suggestions from decisions, and append only within your request. It also works with the authenticated CLI when MCP is unavailable.",
    "skillInstallTitle": "Add the Skill to your working project",
    "skillInstallBody": "In the project where you use Codex, run the commands below, replacing the source repository path. Or download SKILL.md and save it at .agents/skills/event-context/SKILL.md. If that file already exists, review and merge it before replacing it. Other agents should use their own supported Skill directory.",
    "downloadSkill": "Download SKILL.md",
    "viewSkill": "Read the full Skill",
    "skillTryTitle": "Try it in a new conversation",
    "skillTryBody": "Replace PROJECT_ID with your project. In Codex, invoke $event-context. If it does not appear, restart Codex. Other agents can load the file explicitly.",
    "agentPrompt": "$event-context Read project PROJECT_ID and summarize the confirmed decisions and open questions, citing event IDs. Read only for now.",
    "skillVerify": "Expected result: a summary citing real event IDs, with no new record created. Next, ask the agent to save a specific decision; it should return the new event ID, which you can verify with edc get --event EVENT_ID.",
    "skillBoundary": "This is an Agent instruction Skill. The server’s audio-transcribe and daily-review packages are separate automation stages that also require server configuration and a runner; copying this file does not enable them.",
    "skillDocs": "Codex Skill documentation ↗",
    "setupReadme": "Full CLI, HTTP and deployment reference ↗",
    "copiedCode": "Copied",
    "copyFailed": "Could not copy automatically. The text is selected; copy it manually."
  },
  "zh-CN": {
    "title": "Context — 换一个对话，接着往前走。",
    "description": "留下项目中的原始记录，为下一次 AI 对话带去有依据的背景，让工作持续推进。",
    "skip": "跳至正文",
    "navHow": "如何使用",
    "navTrust": "有据可循",
    "navNext": "产品进展",
    "login": "进入工作区",
    "lang": "语言",
    "eyebrow": "EVENT-DRIVEN CONTEXT",
    "hero1": "换一个对话，",
    "hero2": "接着往前走。",
    "heroBody": "决定、想法和项目的来龙去脉，不该止步于一段聊天。留下原始记录，让下一次对话带着背景继续。",
    "cta": "从一条记录开始",
    "demoLink": "看看它如何工作",
    "heroNote": "为在多个 AI 对话中，持续推进项目的人而做。",
    "demoLabel": "CONTEXT 如何连接",
    "demoTag": "概念示例",
    "project": "项目 / 工作室启动",
    "records": "你的原始记录",
    "r1type": "最初的决定",
    "r1": "启动预算定为 5 万元。",
    "r2type": "明确的更新",
    "r2": "预算改为 3 万元，取代之前的决定。",
    "r3type": "尚未确认的建议",
    "r3": "可以考虑邀请一位外部设计师。",
    "newChat": "一段新的对话",
    "qBudget": "现在预算多少？",
    "qNext": "哪些已经决定？",
    "qGap": "还有什么待确认？",
    "answerBudget": "当前预算是 3 万元。明确的更新已经取代了最初 5 万元的决定。",
    "answerNext": "预算已确定为 3 万元。邀请外部设计师仍然只是建议，还不是已确认的安排。",
    "answerGap": "是否邀请外部设计师尚未确认。已有记录只提出了建议，没有最终决定。",
    "sourceBudget": "依据 · 记录 01 + 02",
    "sourceNext": "依据 · 记录 02 + 03",
    "sourceGap": "依据 · 记录 03",
    "sourceNote": "每个结论，都能沿着依据回到原文。",
    "stripLabel": "同一个项目，连贯的上下文。",
    "web": "网页",
    "cli": "CLI",
    "mcp": "MCP",
    "recordStrip": "记录一次，让背景跟上你的工作。",
    "howKicker": "01 / 让工作连起来",
    "howTitle": "少一点重复交代，\n多一点继续向前。",
    "howBody": "把工作背后的信息留下来，让上下文围绕你此刻要做的事展开。",
    "captureTitle": "留下发生过的事。",
    "captureBody": "通过网页、CLI 或 MCP 保存文本和原始文本文件。每条记录保留作者、时间和你定义的 metadata。",
    "available": "已有基础能力",
    "captureFoot": "01 — 记录",
    "contextTitle": "带着背景，问下一个问题。",
    "contextBody": "产品方向：让 agent 按当前任务提取相关决定、约束和未完成事项，并带上可检查的来源。",
    "planned": "规划中",
    "contextFoot": "02 — 提取",
    "skillTitle": "让有用的整理主动发生。",
    "skillBody": "安装 skill，将录音转成文字，或获得一份每日回顾。项目范围、处理提示词和执行环境都由你选择。",
    "skillFoot": "03 — 推进",
    "trustKicker": "02 / 让依据留下来",
    "trustTitle": "答案有用，\n出处让它值得检查。",
    "trustBody": "Context 的设计将原始记录与 agent 的判断分开。你能看清说过什么、改过什么，以及哪些地方还需要自己判断。",
    "trust1Title": "原文保留原样。",
    "trust1Body": "记录只能追加。纠正也是一条新记录，早先的信息仍然可查。",
    "trust2Title": "建议不等于决定。",
    "trust2Body": "上下文提取的设计会区分一个想法与经过你明确确认的决定。",
    "trust3Title": "项目就是共享边界。",
    "trust3Body": "成员可读取项目历史并追加记录。私人信息放在私人项目里。",
    "nextKicker": "03 / 产品正在走向哪里",
    "nextTitle": "从一段语音，到一份每日回顾",
    "nextBody": "我们从一个有用的闭环开始。这是今天已有的基础，以及产品设计中的下一步。",
    "now": "现在",
    "nowTitle": "留下一份共享的项目记录",
    "nowBody": "项目与成员、文本与文本文件、metadata 查询，以及 HTTP、CLI 和 MCP 接入。",
    "next": "下一轮验证",
    "nextText": "音频上传、skill 转录、带依据的上下文提取，以及收件箱里的定时回顾。",
    "later": "后续探索",
    "laterTitle": "让更多信息，带来有用的行动",
    "laterBody": "图片分析、提醒、推荐，以及在明确配置权限后进行分享。",
    "closeTitle": "留下上下文，\n把事情继续下去。",
    "closeBody": "从一个项目，和下一个值得记住的决定开始。",
    "footer": "Integ.Life 出品",
    "footerNote": "原始记录，持续生长的上下文。",
    "roadmapTitle": "从记下来，\n到帮你持续推进。",
    "navConnect": "CLI 与 Agent 接入",
    "connectKicker": "04 / 连接你的工具",
    "connectTitle": "让项目上下文，\n进入 Agent 的工作流。",
    "connectBody": "先用 CLI 跑通记录，再通过 MCP 连接 Agent，最后添加 Skill，约定如何读取、引用和保存上下文。",
    "cliChoice": "在终端直接读取和保存",
    "mcpChoice": "让 Agent 调用项目工具",
    "skillChoice": "告诉 Agent 何时、如何使用上下文",
    "setupIntro": "以下以你自己的本地实例为例。已有服务时，只需安装 CLI，并将 EDC_SERVER 换成该实例的 HTTPS 地址。CLI 与 MCP 使用同一账号和配置文件。",
    "cliTitle": "CLI · 安装、登录、保存第一条记录",
    "cliBuildTitle": "构建并启动本地服务",
    "cliBuildBody": "需要 Git、Make 和 Go 1.26.5 或更新版本。在终端运行，并保持服务进程开启。服务监听 127.0.0.1:8080，数据保存在仓库的 data 目录。已有实例时可跳过启动服务。",
    "cliLoginTitle": "登录并选择项目",
    "cliLoginBody": "打开第二个终端，将仓库路径和 alice 换成你的实际值。已有账号可跳过 register。密码在终端私密输入，长度为 12–72 字节。登录令牌会保存到本地，无需放进对话。",
    "cliRecordTitle": "追加一条记录，再查询验证",
    "cliRecordBody": "将 PROJECT_ID 换成 project create 或 project list 返回的 id。查询应返回刚保存的记录，以及事件 ID、作者和时间。--server、--config 等全局参数必须放在命令前面。",
    "cliNote": "命令输出 JSON。query 返回一页记录；继续查询时，将 next_cursor 作为 --cursor 传入，并保持其他条件不变。需重试的写入请指定唯一的 --idempotency-key，同一次写入重试时复用该键。",
    "mcpTitle": "MCP · 将 Agent 连接到项目",
    "mcpLocalTitle": "本地 Agent：stdio",
    "mcpLocalBody": "先完成 CLI 登录。edc mcp 是连接服务的本地桥接进程，不会创建另一份数据库。替换下面两个绝对路径；config.json 必须是登录时使用的文件，即上面的 EDC_CONFIG 路径。Agent 所在机器需要能够访问这些文件和服务。",
    "mcpJSONBody": "支持 mcpServers JSON 的客户端，可以将此条目合并到其 MCP 配置中。与上面的 Codex 命令二选一，不必重复注册。",
    "mcpVerify": "重新连接或重启 Agent 的 MCP 连接。让它通过 list_projects 列出你的 Context 项目，再通过 query_events 读取其中一个。能看到真实项目和前面保存的记录，才说明接入成功；仅出现在配置列表里还不够。",
    "mcpRemoteTitle": "远程 Agent：Streamable HTTP",
    "mcpRemoteBody": "无法启动本地进程的 Agent，可以配置你自己的、可访问的 HTTPS 地址与 Bearer 认证。在客户端的私密连接设置中替换域名和令牌。下面两行是服务地址和 HTTP 请求头，不是终端命令。",
    "mcpOAuth": "若部署已配置公网 base URL 和 OAuth discovery，支持 OAuth 的客户端可使用同一个 /mcp 地址，并通过授权页登录。context:read 允许读取；context:write 允许追加与项目管理。两者仍受项目成员权限约束。",
    "mcpTrouble": "认证失败时，使用相同服务地址和配置路径重新执行 CLI login，然后重连。找不到项目时，检查当前账号与成员身份。远程连接失败时，检查你自己的服务地址是否可达。",
    "mcpDocs": "Codex MCP 官方配置说明 ↗",
    "skillTitleSetup": "Skill · 让 Agent 按固定方式使用上下文",
    "skillSetupBody": "MCP 提供工具，Skill 提供使用说明。这份 event-context Skill 让 Agent 先读相关历史、引用来源、区分建议与决定，再按你的要求追加记录。没有 MCP 时，也可以使用已登录的 CLI。",
    "skillInstallTitle": "将 Skill 放进你正在工作的项目",
    "skillInstallBody": "在你使用 Codex 的项目目录运行以下命令，替换源仓库路径。也可下载 SKILL.md，保存为 .agents/skills/event-context/SKILL.md。若该文件已存在，请先查看并合并内容再替换。其他 Agent 请使用其支持的 Skill 目录。",
    "downloadSkill": "下载 SKILL.md",
    "viewSkill": "查看完整 Skill",
    "skillTryTitle": "在新对话里试一次",
    "skillTryBody": "将 PROJECT_ID 换成你的项目。在 Codex 中使用 $event-context 调用；若未出现，重启 Codex。其他 Agent 可显式加载该文件。",
    "agentPrompt": "$event-context 读取项目 PROJECT_ID，整理已确认的决定和待解决问题，每项附上事件 ID。此次只读取，先不要写入。",
    "skillVerify": "预期结果：得到引用真实事件 ID 的整理，且没有新增记录。随后明确让 Agent 保存一个具体决定；它应返回新事件 ID，可用 edc get --event EVENT_ID 再次核对。",
    "skillBoundary": "这里提供的是 Agent 的操作指引 Skill。服务端 audio-transcribe 和 daily-review 是另两种自动处理阶段，还需要配置服务端和 runner；复制此文件不会启用它们。",
    "skillDocs": "Codex Skill 官方使用说明 ↗",
    "setupReadme": "完整 CLI、HTTP 与自部署说明 ↗",
    "copyCode": "复制",
    "copiedCode": "已复制",
    "copyFailed": "无法自动复制，已选中内容，请手动复制。"
  },
  "ms": {
    "title": "Context — Sambung dari tempat anda berhenti.",
    "description": "Simpan rekod projek dan bawa latar belakang yang relevan ke perbualan AI seterusnya, dengan sumber yang boleh disemak.",
    "skip": "Langkau ke kandungan",
    "navHow": "Cara berfungsi",
    "navTrust": "Berasaskan bukti",
    "navNext": "Perkembangan",
    "login": "Buka ruang kerja",
    "lang": "Bahasa",
    "eyebrow": "EVENT-DRIVEN CONTEXT",
    "hero1": "Perbualan baharu.",
    "hero2": "Teruskan usaha.",
    "heroBody": "Keputusan, idea dan sejarah projek anda tidak sepatutnya berakhir bersama perbualan. Simpan rekod asal. Bawa konteks ke perbualan seterusnya.",
    "cta": "Mulakan dengan rekod",
    "demoLink": "Terokai konsep",
    "heroNote": "Untuk mereka yang memajukan projek melalui pelbagai perbualan AI.",
    "demoLabel": "CONTEXT DALAM TINDAKAN",
    "demoTag": "Contoh konsep",
    "project": "Projek / Pelancaran studio",
    "records": "Rekod asal anda",
    "r1type": "KEPUTUSAN AWAL",
    "r1": "Tetapkan bajet pelancaran pada ¥50,000.",
    "r2type": "KEMAS KINI JELAS",
    "r2": "Ubah bajet kepada ¥30,000, menggantikan keputusan terdahulu.",
    "r3type": "CADANGAN BELUM DISAHKAN",
    "r3": "Pertimbangkan untuk menjemput pereka luar.",
    "newChat": "Perbualan baharu",
    "qBudget": "Berapa bajetnya?",
    "qNext": "Apa yang diputuskan?",
    "qGap": "Apa belum dipastikan?",
    "answerBudget": "Bajet semasa ialah ¥30,000. Kemas kini yang jelas menggantikan keputusan awal ¥50,000.",
    "answerNext": "Bajet disahkan pada ¥30,000. Melibatkan pereka luar masih satu cadangan, bukan komitmen.",
    "answerGap": "Belum ada keputusan yang disahkan tentang pereka luar. Rekod yang ada hanyalah cadangan.",
    "sourceBudget": "Sumber · rekod 01 + 02",
    "sourceNext": "Sumber · rekod 02 + 03",
    "sourceGap": "Sumber · rekod 03",
    "sourceNote": "Jejaki bukti kembali kepada rekod asal.",
    "stripLabel": "SATU PROJEK. KONTEKS BERSAMBUNG.",
    "web": "Web",
    "cli": "CLI",
    "mcp": "MCP",
    "recordStrip": "Catat sekali. Bawa latar belakang bersama.",
    "howKicker": "01 / KESINAMBUNGAN KERJA",
    "howTitle": "Kurang mengulang.\nLebih banyak kemajuan.",
    "howBody": "Tempat untuk maklumat di sebalik kerja anda, dengan konteks mengikut keperluan semasa.",
    "captureTitle": "Simpan apa yang berlaku.",
    "captureBody": "Simpan teks dan fail teks asal melalui web, CLI atau MCP. Setiap rekod menyimpan penulis, masa dan metadata.",
    "available": "Asas tersedia",
    "captureFoot": "01 — REKOD",
    "contextTitle": "Tanya dengan latar yang tepat.",
    "contextBody": "Hala tuju: agent mendapatkan keputusan, kekangan dan soalan terbuka yang relevan dengan tugas, berserta sumber bukti.",
    "planned": "Dirancang",
    "contextFoot": "02 — DAPATKAN",
    "skillTitle": "Biarkan kerja berguna datang kepada anda.",
    "skillBody": "Pasang skill untuk menukar rakaman kepada teks atau menyediakan ulasan harian. Pilih projek, arahan dan persekitaran pelaksanaannya.",
    "skillFoot": "03 — TERUSKAN",
    "trustKicker": "02 / SIMPAN BUKTI",
    "trustTitle": "Jawapan itu berguna.\nSumbernya boleh disemak.",
    "trustBody": "Context direka untuk membezakan rekod asal daripada kesimpulan agent. Lihat apa yang dikatakan, apa yang berubah dan apa yang masih memerlukan pertimbangan anda.",
    "trust1Title": "Rekod asal kekal.",
    "trust1Body": "Rekod hanya boleh ditambah. Pembetulan menjadi rekod baharu, jadi maklumat terdahulu masih tersedia.",
    "trust2Title": "Cadangan kekal sebagai cadangan.",
    "trust2Body": "Aliran konteks yang dirancang membezakan idea daripada keputusan yang anda sahkan.",
    "trust3Title": "Projek menetapkan sempadan.",
    "trust3Body": "Ahli boleh membaca dan menambah rekod dalam projek. Simpan maklumat peribadi dalam projek peribadi.",
    "nextKicker": "03 / HALA TUJU KAMI",
    "nextTitle": "Dari nota suara ke ulasan harian",
    "nextBody": "Kami membangunkan Context satu aliran berguna pada satu masa. Inilah asas semasa dan langkah seterusnya dalam reka bentuk produk.",
    "now": "SEKARANG",
    "nowTitle": "Rekod projek yang dikongsi",
    "nowBody": "Projek, ahli, teks dan fail teks, carian metadata serta akses HTTP, CLI dan MCP.",
    "next": "PENGESAHAN SETERUSNYA",
    "nextText": "Muat naik audio, transkripsi melalui skill, pengambilan konteks dengan bukti dan ulasan berjadual dalam peti masuk.",
    "later": "PENEROKAAN",
    "laterTitle": "Lebih banyak cara menggunakan konteks",
    "laterBody": "Analisis imej, peringatan, cadangan dan perkongsian dengan kebenaran yang ditetapkan secara jelas.",
    "closeTitle": "Simpan konteks.\nTeruskan kerja.",
    "closeBody": "Mulakan dengan satu projek dan keputusan seterusnya yang patut diingati.",
    "footer": "Produk oleh Integ.Life",
    "footerNote": "Rekod asal. Konteks berterusan.",
    "roadmapTitle": "Bermula dengan rekod.\nMenuju rutin yang membantu.",
    "navConnect": "CLI & Agent",
    "connectKicker": "04 / SAMBUNGKAN ALAT",
    "connectTitle": "Konteks projek.\nDalam aliran kerja agent.",
    "connectBody": "Mulakan dengan CLI, sambungkan agent melalui MCP, kemudian tambah Skill untuk membimbing pembacaan dan penyimpanan konteks.",
    "cliChoice": "Baca dan simpan melalui terminal",
    "mcpChoice": "Beri agent akses kepada alat projek",
    "skillChoice": "Panduan bila dan cara menggunakan konteks",
    "setupIntro": "Contoh ini menggunakan pelayan setempat anda. Jika sudah ada pelayan, bina CLI dan tukar EDC_SERVER kepada alamat HTTPS pelayan itu. Gunakan akaun dan fail konfigurasi yang sama untuk CLI dan MCP.",
    "cliTitle": "CLI · Pasang, log masuk, simpan rekod",
    "cliBuildTitle": "Bina dan jalankan pelayan setempat",
    "cliBuildBody": "Perlu Git, Make dan Go 1.26.5 atau lebih baharu. Jalankan dalam terminal dan biarkan pelayan berjalan. Alamatnya 127.0.0.1:8080; data disimpan dalam direktori data repositori. Langkau pelancaran pelayan jika anda sudah mempunyai pelayan.",
    "cliLoginTitle": "Log masuk dan pilih projek",
    "cliLoginBody": "Buka terminal kedua. Gantikan laluan repositori dan alice. Pengguna sedia ada boleh melangkau register. Masukkan kata laluan secara sulit dalam terminal (12–72 bait). Token disimpan secara setempat, bukan dalam perbualan.",
    "cliRecordTitle": "Tambah rekod, kemudian baca semula",
    "cliRecordBody": "Gantikan PROJECT_ID dengan id daripada project create atau project list. Pertanyaan sepatutnya memulangkan rekod tadi bersama ID acara, penulis dan masa. Pilihan global --server dan --config mesti mendahului arahan.",
    "cliNote": "Output ialah JSON. query memulangkan satu halaman; gunakan next_cursor sebagai --cursor dengan penapis yang sama untuk halaman seterusnya. Tetapkan --idempotency-key unik bagi setiap penulisan dan guna semula hanya untuk percubaan penulisan yang sama.",
    "mcpTitle": "MCP · Sambungkan agent anda",
    "mcpLocalTitle": "Agent setempat: stdio",
    "mcpLocalBody": "Log masuk melalui CLI dahulu. edc mcp ialah jambatan ke pelayan, bukan pangkalan data lain. Gantikan kedua-dua laluan mutlak. config.json mesti sama dengan fail EDC_CONFIG semasa log masuk. Mesin agent perlu boleh mencapai fail dan pelayan tersebut.",
    "mcpJSONBody": "Untuk klien yang menerima JSON mcpServers, gabungkan entri ini ke dalam konfigurasi MCP. Pilih ini atau arahan Codex di atas; daftar sekali sahaja.",
    "mcpVerify": "Sambung semula MCP atau mulakan semula agent. Minta list_projects menyenaraikan projek Context anda, kemudian query_events membaca satu projek. Pastikan projek sebenar dan rekod tadi muncul; senarai konfigurasi sahaja belum membuktikan akses.",
    "mcpRemoteTitle": "Agent jauh: Streamable HTTP",
    "mcpRemoteBody": "Jika agent tidak boleh menjalankan proses setempat, gunakan alamat HTTPS pelayan anda dan pengesahan Bearer. Gantikan hos dan token dalam tetapan sambungan peribadi klien. Dua baris ini ialah alamat dan pengepala HTTP, bukan arahan terminal.",
    "mcpOAuth": "Klien OAuth boleh menggunakan URL /mcp yang sama apabila pelayan mempunyai URL awam dan penemuan OAuth. Log masuk melalui halaman kebenaran. context:read membolehkan bacaan; context:write membolehkan penambahan dan pengurusan projek. Keahlian projek tetap diperlukan.",
    "mcpTrouble": "Jika pengesahan gagal, ulang CLI login dengan pelayan dan laluan konfigurasi yang sama, kemudian sambung semula. Jika projek tiada, semak akaun dan keahlian. Untuk kegagalan jauh, semak capaian pelayan anda.",
    "mcpDocs": "Dokumentasi MCP Codex ↗",
    "skillTitleSetup": "Skill · Panduan aliran kerja agent",
    "skillSetupBody": "MCP menyediakan alat; Skill menyediakan arahan. Skill event-context membaca sejarah berkaitan, memetik sumber, membezakan cadangan daripada keputusan dan menambah rekod mengikut permintaan anda. CLI yang telah dilog masuk boleh digunakan tanpa MCP.",
    "skillInstallTitle": "Tambah Skill ke projek kerja anda",
    "skillInstallBody": "Jalankan arahan ini dalam projek yang anda gunakan dengan Codex. Gantikan laluan repositori sumber. Atau muat turun SKILL.md ke .agents/skills/event-context/SKILL.md. Jika fail sudah wujud, semak dan gabungkan dahulu. Untuk agent lain, gunakan direktori Skill yang disokongnya.",
    "downloadSkill": "Muat turun SKILL.md",
    "viewSkill": "Baca Skill penuh",
    "skillTryTitle": "Cuba dalam perbualan baharu",
    "skillTryBody": "Gantikan PROJECT_ID dengan projek anda. Gunakan $event-context dalam Codex; mulakan semula Codex jika ia tidak muncul. Agent lain boleh memuatkan fail secara jelas.",
    "agentPrompt": "$event-context Baca projek PROJECT_ID. Ringkaskan keputusan yang disahkan dan soalan terbuka, berserta ID acara. Baca sahaja buat masa ini; jangan tambah rekod.",
    "skillVerify": "Hasil dijangka: ringkasan dengan ID acara sebenar, tanpa rekod baharu. Kemudian minta agent menyimpan satu keputusan tertentu; sahkan ID acara yang dipulangkan dengan edc get --event EVENT_ID.",
    "skillBoundary": "Ini ialah Skill arahan untuk agent. Pakej pelayan audio-transcribe dan daily-review ialah peringkat automasi berasingan yang memerlukan konfigurasi pelayan dan runner; menyalin fail ini tidak mengaktifkannya.",
    "skillDocs": "Dokumentasi Skill Codex ↗",
    "setupReadme": "Rujukan penuh CLI, HTTP dan pemasangan pelayan ↗",
    "copyCode": "Salin",
    "copiedCode": "Disalin",
    "copyFailed": "Salinan automatik gagal. Teks dipilih; sila salin secara manual."
  },
  "hi": {
    "title": "Context — जहाँ रुके थे, वहीं से आगे बढ़ें।",
    "description": "अपने प्रोजेक्ट के रिकॉर्ड सहेजें और जाँचे जा सकने वाले स्रोतों के साथ अगली AI बातचीत में सही संदर्भ लाएँ।",
    "skip": "मुख्य सामग्री पर जाएँ",
    "navHow": "कैसे काम करता है",
    "navTrust": "साक्ष्य पर आधारित",
    "navNext": "आगे की योजना",
    "login": "कार्यक्षेत्र खोलें",
    "lang": "भाषा",
    "eyebrow": "EVENT-DRIVEN CONTEXT",
    "hero1": "नई बातचीत।",
    "hero2": "काम जारी रहे।",
    "heroBody": "आपके निर्णय, विचार और प्रोजेक्ट का इतिहास एक चैट के साथ खत्म नहीं होने चाहिए। मूल रिकॉर्ड सहेजें और अगली बातचीत में सही संदर्भ के साथ आगे बढ़ें।",
    "cta": "एक रिकॉर्ड से शुरू करें",
    "demoLink": "विचार को समझें",
    "heroNote": "उन लोगों के लिए जो कई AI बातचीत में एक प्रोजेक्ट को आगे बढ़ाते हैं।",
    "demoLabel": "CONTEXT का उदाहरण",
    "demoTag": "अवधारणा का उदाहरण",
    "project": "प्रोजेक्ट / स्टूडियो की शुरुआत",
    "records": "आपके मूल रिकॉर्ड",
    "r1type": "शुरुआती निर्णय",
    "r1": "शुरुआत का बजट ¥50,000 तय करें।",
    "r2type": "स्पष्ट बदलाव",
    "r2": "पहले निर्णय की जगह बजट ¥30,000 करें।",
    "r3type": "अपुष्ट सुझाव",
    "r3": "किसी बाहरी डिज़ाइनर को बुलाने पर विचार करें।",
    "newChat": "एक नई बातचीत",
    "qBudget": "बजट कितना है?",
    "qNext": "क्या तय हो गया है?",
    "qGap": "क्या अभी खुला है?",
    "answerBudget": "वर्तमान बजट ¥30,000 है। स्पष्ट बदलाव ने पहले के ¥50,000 वाले निर्णय की जगह ली है।",
    "answerNext": "बजट ¥30,000 तय है। बाहरी डिज़ाइनर को शामिल करना अभी सुझाव है, कोई पक्का निर्णय नहीं।",
    "answerGap": "बाहरी डिज़ाइनर पर कोई पक्का निर्णय नहीं है। उपलब्ध रिकॉर्ड केवल एक सुझाव है।",
    "sourceBudget": "स्रोत · रिकॉर्ड 01 + 02",
    "sourceNext": "स्रोत · रिकॉर्ड 02 + 03",
    "sourceGap": "स्रोत · रिकॉर्ड 03",
    "sourceNote": "साक्ष्य से मूल रिकॉर्ड तक पहुँचें।",
    "stripLabel": "एक प्रोजेक्ट। जुड़ा हुआ संदर्भ।",
    "web": "वेब",
    "cli": "CLI",
    "mcp": "MCP",
    "recordStrip": "एक बार दर्ज करें। संदर्भ साथ लेकर आगे बढ़ें।",
    "howKicker": "01 / काम की निरंतरता",
    "howTitle": "कम दोहराएँ।\nज़्यादा आगे बढ़ें।",
    "howBody": "आपके काम के पीछे की जानकारी के लिए एक जगह, जहाँ संदर्भ आपकी वर्तमान ज़रूरत के अनुसार हो।",
    "captureTitle": "जो हुआ, उसे सहेजें।",
    "captureBody": "वेब, CLI या MCP से टेक्स्ट और मूल टेक्स्ट फ़ाइलें सहेजें। हर रिकॉर्ड में लेखक, समय और metadata रहता है।",
    "available": "आधार उपलब्ध",
    "captureFoot": "01 — दर्ज करें",
    "contextTitle": "सही पृष्ठभूमि के साथ पूछें।",
    "contextBody": "उद्देश्य: आपका agent वर्तमान काम से जुड़े निर्णय, सीमाएँ और खुले प्रश्न स्रोतों के साथ प्राप्त करे।",
    "planned": "योजनाबद्ध",
    "contextFoot": "02 — संदर्भ लें",
    "skillTitle": "उपयोगी काम खुद आप तक आए।",
    "skillBody": "रिकॉर्डिंग को टेक्स्ट में बदलने या दैनिक समीक्षा के लिए skill स्थापित करें। उसका प्रोजेक्ट, निर्देश और चलाने का परिवेश चुनें।",
    "skillFoot": "03 — आगे बढ़ें",
    "trustKicker": "02 / साक्ष्य बनाए रखें",
    "trustTitle": "जवाब उपयोगी है।\nस्रोत उसे जाँचने योग्य बनाता है।",
    "trustBody": "Context का डिज़ाइन मूल रिकॉर्ड और agent के निष्कर्ष को अलग रखता है। देखें कि क्या कहा गया, क्या बदला और कहाँ आपके निर्णय की ज़रूरत है।",
    "trust1Title": "मूल रिकॉर्ड जस के तस।",
    "trust1Body": "रिकॉर्ड केवल जोड़े जाते हैं। सुधार एक नया रिकॉर्ड होता है, इसलिए पुरानी जानकारी उपलब्ध रहती है।",
    "trust2Title": "सुझाव, सुझाव ही रहता है।",
    "trust2Body": "प्रस्तावित संदर्भ प्रक्रिया किसी विचार और आपके द्वारा पुष्टि किए गए निर्णय में अंतर रखती है।",
    "trust3Title": "प्रोजेक्ट सीमा तय करते हैं।",
    "trust3Body": "सदस्य प्रोजेक्ट में पढ़ सकते हैं और रिकॉर्ड जोड़ सकते हैं। निजी जानकारी निजी प्रोजेक्ट में रखें।",
    "nextKicker": "03 / आगे की दिशा",
    "nextTitle": "वॉइस नोट से दैनिक समीक्षा तक",
    "nextBody": "हम एक समय में एक उपयोगी प्रक्रिया बना रहे हैं। यह वर्तमान आधार और उत्पाद डिज़ाइन के अगले कदम हैं।",
    "now": "आज",
    "nowTitle": "आपके प्रोजेक्ट का साझा रिकॉर्ड",
    "nowBody": "प्रोजेक्ट, सदस्य, टेक्स्ट और टेक्स्ट फ़ाइलें, metadata खोज और HTTP, CLI व MCP से पहुँच।",
    "next": "अगला सत्यापन",
    "nextText": "ऑडियो अपलोड, skill द्वारा ट्रांसक्रिप्शन, साक्ष्य के साथ संदर्भ और इनबॉक्स में निर्धारित समीक्षा।",
    "later": "आगे के विचार",
    "laterTitle": "संदर्भ को उपयोगी बनाने के और तरीके",
    "laterBody": "छवि विश्लेषण, रिमाइंडर, सुझाव और स्पष्ट रूप से तय अनुमतियों के साथ साझा करना।",
    "closeTitle": "संदर्भ सहेजें।\nकाम जारी रखें।",
    "closeBody": "एक प्रोजेक्ट और याद रखने लायक अगले निर्णय से शुरू करें।",
    "footer": "Integ.Life का एक उत्पाद",
    "footerNote": "मूल रिकॉर्ड। निरंतर संदर्भ।",
    "roadmapTitle": "रिकॉर्ड से शुरू करें।\nमददगार दिनचर्या की ओर बढ़ें।",
    "navConnect": "CLI और Agent",
    "connectKicker": "04 / अपने टूल जोड़ें",
    "connectTitle": "प्रोजेक्ट का संदर्भ।\nआपके agent के काम में।",
    "connectBody": "CLI से शुरुआत करें, MCP से agent जोड़ें और संदर्भ पढ़ने व सहेजने के निर्देश देने के लिए Skill जोड़ें।",
    "cliChoice": "टर्मिनल से पढ़ें और सहेजें",
    "mcpChoice": "Agent को प्रोजेक्ट के टूल दें",
    "skillChoice": "संदर्भ कब और कैसे उपयोग करना है, बताएँ",
    "setupIntro": "यह उदाहरण आपके स्थानीय सर्वर के लिए है। सर्वर पहले से है तो CLI बनाएँ और EDC_SERVER में उसका HTTPS पता दें। CLI और MCP में एक ही खाता और कॉन्फ़िगरेशन फ़ाइल रखें।",
    "cliTitle": "CLI · स्थापित करें, लॉग इन करें, रिकॉर्ड सहेजें",
    "cliBuildTitle": "स्थानीय सर्वर बनाएँ और चलाएँ",
    "cliBuildBody": "Git, Make और Go 1.26.5 या नया संस्करण चाहिए। टर्मिनल में चलाएँ और सर्वर चालू रखें। पता 127.0.0.1:8080 है; डेटा रिपॉज़िटरी के data फ़ोल्डर में रहेगा। सर्वर पहले से है तो उसे शुरू करने का चरण छोड़ें।",
    "cliLoginTitle": "लॉग इन करें और प्रोजेक्ट चुनें",
    "cliLoginBody": "दूसरा टर्मिनल खोलें। रिपॉज़िटरी का पथ और alice बदलें। खाता पहले से है तो register छोड़ें। पासवर्ड टर्मिनल में निजी रूप से दर्ज करें (12–72 बाइट)। टोकन स्थानीय फ़ाइल में सहेजा जाता है; उसे बातचीत में न डालें।",
    "cliRecordTitle": "रिकॉर्ड जोड़ें और पढ़कर जाँचें",
    "cliRecordBody": "PROJECT_ID को project create या project list से मिले id से बदलें। क्वेरी में नया रिकॉर्ड, उसका इवेंट ID, लेखक और समय दिखना चाहिए। --server और --config जैसे वैश्विक विकल्प कमांड से पहले रखें।",
    "cliNote": "आउटपुट JSON है। query एक पृष्ठ देता है; अगले पृष्ठ के लिए समान फ़िल्टर के साथ next_cursor को --cursor में दें। हर लेखन के लिए अलग --idempotency-key दें और केवल उसी लेखन को दोहराते समय उसका फिर उपयोग करें।",
    "mcpTitle": "MCP · अपना agent जोड़ें",
    "mcpLocalTitle": "स्थानीय agent: stdio",
    "mcpLocalBody": "पहले CLI से लॉग इन करें। edc mcp सर्वर से जुड़ने वाला पुल है, अलग डेटाबेस नहीं। दोनों पूर्ण पथ बदलें। config.json वही EDC_CONFIG फ़ाइल होनी चाहिए जो लॉग इन में उपयोग हुई। Agent की मशीन को फ़ाइलों और सर्वर तक पहुँच चाहिए।",
    "mcpJSONBody": "mcpServers JSON स्वीकार करने वाले क्लाइंट की MCP कॉन्फ़िगरेशन में यह प्रविष्टि मिलाएँ। यह तरीका या ऊपर का Codex कमांड चुनें; एक बार पंजीकरण पर्याप्त है।",
    "mcpVerify": "Agent का MCP कनेक्शन फिर जोड़ें या पुनः शुरू करें। list_projects से अपने Context प्रोजेक्ट दिखाने और query_events से एक प्रोजेक्ट पढ़ने को कहें। असली प्रोजेक्ट और पहले सहेजा रिकॉर्ड दिखना पहुँच का प्रमाण है; केवल कॉन्फ़िगरेशन सूची पर्याप्त नहीं।",
    "mcpRemoteTitle": "दूरस्थ agent: Streamable HTTP",
    "mcpRemoteBody": "स्थानीय प्रक्रिया शुरू न कर सकने वाले agent के लिए अपने सर्वर का उपलब्ध HTTPS पता और Bearer प्रमाणीकरण दें। क्लाइंट की निजी कनेक्शन सेटिंग में होस्ट और टोकन बदलें। नीचे पता और HTTP हेडर हैं, टर्मिनल कमांड नहीं।",
    "mcpOAuth": "सर्वर पर सार्वजनिक base URL और OAuth discovery सेट होने पर OAuth क्लाइंट उसी /mcp URL का उपयोग कर सकते हैं। अनुमति पृष्ठ से लॉग इन करें। context:read पढ़ने और context:write जोड़ने व प्रोजेक्ट प्रबंधन के लिए है। प्रोजेक्ट सदस्यता की जाँच दोनों में होती है।",
    "mcpTrouble": "प्रमाणीकरण विफल हो तो उसी सर्वर और कॉन्फ़िगरेशन पथ के साथ CLI login दोहराएँ और फिर जोड़ें। प्रोजेक्ट न दिखे तो खाता और सदस्यता जाँचें। दूरस्थ कनेक्शन विफल हो तो अपने सर्वर की उपलब्धता जाँचें।",
    "mcpDocs": "Codex MCP के आधिकारिक निर्देश ↗",
    "skillTitleSetup": "Skill · Agent के काम करने का तरीका तय करें",
    "skillSetupBody": "MCP टूल देता है; Skill निर्देश देता है। event-context Skill संबंधित इतिहास पढ़ने, स्रोत देने, सुझाव और निर्णय अलग रखने तथा आपके अनुरोध के अनुसार रिकॉर्ड जोड़ने में मदद करता है। MCP न हो तो लॉग इन किया हुआ CLI उपयोग कर सकता है।",
    "skillInstallTitle": "अपने कार्य प्रोजेक्ट में Skill जोड़ें",
    "skillInstallBody": "Codex वाले प्रोजेक्ट में ये कमांड चलाएँ और स्रोत रिपॉज़िटरी का पथ बदलें। या SKILL.md डाउनलोड करके .agents/skills/event-context/SKILL.md में रखें। फ़ाइल पहले से हो तो बदलने से पहले पढ़कर सामग्री मिलाएँ। अन्य agent के लिए उसका समर्थित Skill फ़ोल्डर उपयोग करें।",
    "downloadSkill": "SKILL.md डाउनलोड करें",
    "viewSkill": "पूरा Skill पढ़ें",
    "skillTryTitle": "नई बातचीत में आज़माएँ",
    "skillTryBody": "PROJECT_ID को अपने प्रोजेक्ट से बदलें। Codex में $event-context उपयोग करें। न दिखे तो Codex फिर शुरू करें। अन्य agent को फ़ाइल स्पष्ट रूप से पढ़ने को कह सकते हैं।",
    "agentPrompt": "$event-context प्रोजेक्ट PROJECT_ID पढ़ें। पुष्टि किए गए निर्णय और खुले प्रश्न बताएँ, हर बिंदु के साथ इवेंट ID दें। अभी केवल पढ़ें, नया रिकॉर्ड न जोड़ें।",
    "skillVerify": "अपेक्षित परिणाम: असली इवेंट ID वाला सारांश, कोई नया रिकॉर्ड नहीं। फिर किसी विशेष निर्णय को सहेजने को कहें; मिले नए इवेंट ID को edc get --event EVENT_ID से जाँचें।",
    "skillBoundary": "यह agent के लिए निर्देश वाला Skill है। सर्वर के audio-transcribe और daily-review अलग स्वचालन चरण हैं, जिनके लिए सर्वर और runner कॉन्फ़िगरेशन चाहिए। इस फ़ाइल को कॉपी करने से वे चालू नहीं होते।",
    "skillDocs": "Codex Skill के आधिकारिक निर्देश ↗",
    "setupReadme": "CLI, HTTP और स्वयं होस्ट करने का पूरा विवरण ↗",
    "copyCode": "कॉपी करें",
    "copiedCode": "कॉपी हो गया",
    "copyFailed": "अपने-आप कॉपी नहीं हुआ। चुने हुए टेक्स्ट को मैन्युअल रूप से कॉपी करें।"
  }
};
